### ISSUE TITLE
Ecotracker Bezug wird nicht angezeigt

### ISSUE THREAD

**Issue by dummbold** [Selbstbau-PV/Ecotracker-Daten-im-Home-Assistant-anzeigen#3]
Ich habe die Ecotracker Entitäten gemäß den Vorgaben in der configuration.yaml eingetragen.

```
 - sensor:
    - name: "Ecotracker Aktueller Verbrauch"
      device_class: "power"
      state_class: "measurement"
      unit_of_measurement: "W"
      state: >
            {{ state_attr('sensor.ecotracker', 'power') }}

    - name: "Ecotracker Bezug"
      device_class: "energy"
      state_class: "total_increasing"
      unit_of_measurement: "KWh"
      state: >
            {{ iif(state_attr('sensor.ecotracker', 'energyCounterIn'), (state_attr('sensor.ecotracker', 'energyCounterIn') | float/1000)| round(2)) }}

    - name: "Ecotracker Einspeisung"
      device_class: "energy"
      state_class: "total_increasing"
      unit_of_measurement: "kWh"
      state: >
            {{ iif(state_attr('sensor.ecotracker', 'energyCounterOut'), (state_attr('sensor.ecotracker', 'energyCounterOut') | float/1000)| round(2)) }}
          
```

Sie sind in den Entitäten auch zu finden und alle liefern brav Daten.

Aber ich kann den Bezug nicht in die Konfiguration der Energiekarte eintragen! Da wird mir der "_bezug" Sensor nicht angezeigt! Unter Bezug und Einspeisung sehe ich nur den Sensor "_einspeisung".

In der Liste der Entitäten werde ich darauf hingewiesen, dass die drei Sensoren (Verbrauch, Bezug, Einspeisung) keine eindeutige ID haben. Trage ich die händisch in die configuration.yaml ein (z.B. ecotracker_bezug) habe ich auf einmal je 2 Entitäten: einen Sensor und ein Template, wobei der Sensor wieder keine unique-id hat. Beide heißen identisch, ausser dass der Sensor ein _2 am Ende des Namens hat. Wenn es Sinn macht behalte ich beide, dann möchte ich sie aber auch besser benennen - was beim Sensor nicht geht, da keine unique-id.

Und ich sehe nach wie vor bei der Konfiguration nur _einspeisung (allerdings jetzt Template und Sensor), aber keine _bezug.

Bahnhof, Bahnhof, Bahnhof.
Ich glaub ich werd' zum Hirsch hier ... wo ist der Wald, ich sehe nur Bäume um mich rum.
Und jetzt??????
